export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PROFILE_REPOSITORY = Symbol('PROFILE_REPOSITORY');
export const USER_STAT_REPOSITORY = Symbol('USER_STAT_REPOSITORY');

export const EMAIL_VERIFICATION_REPOSITORY = Symbol('EMAIL_VERIFICATION_REPOSITORY');
export const EMAIL_SERVICE = Symbol('EMAIL_SERVICE');
